---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: yes

  tasks:
    - name: Ensure Local User Created
      user:
        name: "{{ custom_user_name }}"
        password: "{{ custom_user_password |password_hash('sha512') }}"
        shell:  /bin/bash
        groups: 
          - wheel
        append: no   # overwrites additional groups.  change to yes to preserve.
        state: present

    - name: Add Local User Authorized SSH Key
      authorized_key:
        user: "{{ custom_user_name }}"
        state: present
        key: "{{ custom_user_ssh_key }}"
      when: custom_user_ssh_key is defined

    - name: Ensure wheel group in sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel ALL='
        line: '%wheel ALL=(ALL)	NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
